version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.10.1
    # environment:
    #   - HTTP_PROXY=http://127.0.0.1:7890
    #   - HTTPS_PROXY=http://127.0.0.1:7890
    #   - NO_PROXY="localhost,127.0.0.1,192.168.0.0/16,172.0.0.0/8,10.0.0.0/8"
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
